In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shamimhasan8/python-code-bug-and-fix-pairs")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/shamimhasan8/python-code-bug-and-fix-pairs?dataset_version_number=1...

100%|██████████| 41.6k/41.6k [00:00<00:00, 2.77MB/s]

Extracting files...
Path to dataset files: /Users/lustrousparadox/.cache/kagglehub/datasets/shamimhasan8/python-code-bug-and-fix-pairs/versions/1

In [3]:
import pandas as pd

data = pd.read_csv("data/code_bug_fix_pairs.csv", header=0)
data

,id,buggy_code,fixed_code,commit_message,commit_url,date
0,1,"x = [1, 2, 3]\nprint x\n# Sample ID: 1","x = [1, 2, 3]\nprint(x)\n# Sample ID: 1",Improved readability with proper indentation,https://github.com/open-source-repo/commit/a5a...,2024-12-16
1,2,"list = [1, 2, 3, 4]\nfor i in list\n print(...","lst = [1, 2, 3, 4]\nfor i in lst:\n print(i...",Corrected conditional operator mistake,https://github.com/open-source-repo/commit/f47...,2024-01-03
2,3,def factorial(n):\n if n == 1\n retu...,def factorial(n):\n if n == 1:\n ret...,Resolved off-by-one error in loop,https://github.com/open-source-repo/commit/e89...,2023-09-05
3,4,def foo()\n print('Missing colon in functio...,def foo():\n print('Fixed missing colon in ...,Added missing parentheses for print function,https://github.com/open-source-repo/commit/bd7...,2024-09-15
4,5,def factorial(n):\n if n == 1\n retu...,def factorial(n):\n if n == 1:\n ret...,Fixed bug in recursive function call,https://github.com/open-source-repo/commit/d66...,2024-01-24
...,...,...,...,...,...,...
995,996,"def greet(name):\n print('Hello, ' + name)\...","def greet(name):\n print('Hello, ' + name)\...",Resolved off-by-one error in loop,https://github.com/open-source-repo/commit/eb3...,2024-08-15
996,997,while True\n do_something()\n# Sample ID: 997,while True:\n do_something()\n# Sample ID: 997,Fixed bug in recursive function call,https://github.com/open-source-repo/commit/fda...,2024-02-21
997,998,if (a > b):\n print('a is greater')\nelse\n...,if (a > b):\n print('a is greater')\nelse:\...,Improved readability with proper indentation,https://github.com/open-source-repo/commit/166...,2024-04-20
998,999,while True\n do_something()\n# Sample ID: 999,while True:\n do_something()\n# Sample ID: 999,Corrected conditional operator mistake,https://github.com/open-source-repo/commit/65c...,2025-06-08
999,1000,def factorial(n):\n if n == 1\n retu...,def factorial(n):\n if n == 1:\n ret...,Resolved off-by-one error in loop,https://github.com/open-source-repo/commit/6d3...,2025-06-25

In [5]:
snippet_df = (
    pd.concat([data["buggy_code"], data["fixed_code"]], ignore_index=True).dropna().to_frame(name="code snippet").sample(frac=1, random_state=42).reset_index(drop=True)
)
snippet_df

                                           code snippet
0     while True:\n    do_something()\n# Sample ID: 861
1      if x = 5:\n    print('x is 5')\n# Sample ID: 354
2     def greet(name):\n    print('Hello, ' + name)\...
3       for i in range(10):\nprint(i)\n# Sample ID: 906
4             x = [1, 2, 3]\nprint(x)\n# Sample ID: 290
...                                                 ...
1995  for i in range(10):\n    print(i)\n# Sample ID...
1996          x = [1, 2, 3]\nprint(x)\n# Sample ID: 295
1997   while True\n    do_something()\n# Sample ID: 861
1998          x = [1, 2, 3]\nprint(x)\n# Sample ID: 460
1999          x = [1, 2, 3]\nprint(x)\n# Sample ID: 127

[2000 rows x 1 columns]

In [6]:
snippet_df = snippet_df.reset_index().rename(columns={"index": "id"})
snippet_df

        id                                       code snippet
0        0  while True:\n    do_something()\n# Sample ID: 861
1        1   if x = 5:\n    print('x is 5')\n# Sample ID: 354
2        2  def greet(name):\n    print('Hello, ' + name)\...
3        3    for i in range(10):\nprint(i)\n# Sample ID: 906
4        4          x = [1, 2, 3]\nprint(x)\n# Sample ID: 290
...    ...                                                ...
1995  1995  for i in range(10):\n    print(i)\n# Sample ID...
1996  1996          x = [1, 2, 3]\nprint(x)\n# Sample ID: 295
1997  1997   while True\n    do_something()\n# Sample ID: 861
1998  1998          x = [1, 2, 3]\nprint(x)\n# Sample ID: 460
1999  1999          x = [1, 2, 3]\nprint(x)\n# Sample ID: 127

[2000 rows x 2 columns]

In [8]:
snippet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            2000 non-null   int64
 1   code snippet  2000 non-null   object
dtypes: int64(1), object(1)
memory usage: 31.4+ KB

In [10]:
snippet_df.to_csv("code_snippets.csv", index=False)